# Generated by Django 4.1 on 2024-10-22 16:05

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='uploads/movies/sample-movie-2d04141c-daba-4877-83d8-abd14b697d76.jpg', upload_to=cinema.models.upload_movie_image_path),
            preserve_default=False,
        ),
    ]
